[project]
name = "l4212t3-sat"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Rafa", email = "65214797+riff-raff-17@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "arcade>=3.3.3",
    "ipykernel>=7.3.0",
    "notebook>=7.6.2",
    "pip>=26.2.1",
]

[project.scripts]
l4212t3-sat = "l4212t3_sat:main"

[build-system]
requires = ["uv_build>=0.12.10,<0.13.0"]
build-backend = "uv_build"
