[project]
name = "term-2"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Rafa", email = "65214797+riff-raff-17@users.noreply.github.com" }
]
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.3.0",
    "pip>=26.2.1",
    "pygame>=2.6.1",
    "ugot>=0.2.13",
]

[project.scripts]
term-2 = "term_2:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
